### PR TITLE
Webpack Es module support for npm package dist

### PR DESCRIPTION
**Pull request by salvoravida**
I have update gulp task with buildEs task that just build plain ES src in distrib/es
updated also package.json with "module" key.

I need this to use it in a ReactJs (create-react-app) app without RequireJS.

Usage :

```javascript
import * as SDK from 'microsoft-speech-browser-sdk';
 
function RecognizerSetup(recognitionMode, language, format, subscriptionKey) {
    let recognizerConfig = new SDK.RecognizerConfig(
        new SDK.SpeechConfig(
            new SDK.Context(
                new SDK.OS(navigator.userAgent, "Browser", null),
                new SDK.Device("SpeechSample", "SpeechSample", "1.0.00000"))),
        recognitionMode, // SDK.RecognitionMode.Interactive 
        language, // Supported laguages are specific to each recognition mode. Refer to docs.
        format); // SDK.SpeechResultFormat.Simple (Options - Simple/Detailed)

    // Alternatively use SDK.CognitiveTokenAuthentication(fetchCallback, fetchOnExpiryCallback) 
    let authentication = new SDK.CognitiveSubscriptionKeyAuthentication(subscriptionKey);

    // return SDK.Recognizer.Create(recognizerConfig, authentication);
    return SDK.CreateRecognizer(recognizerConfig, authentication);
}
```

Maybe it is useful for community!

Regards,
Salvo

### CODE REVIEW

**Comment by salvoravida** [comment]
also fix a fix string template on Mic not allowed error

**Comment by salvoravida** [comment]
better on ES5 for IE support also.

**Comment by seanfcarroll** [comment]
Looking forward to this being merged.

**Comment by raaaar** [comment]
A quick update on this: after integrating this change, microphone no longer picks up audio on iOS, trying to figure what's going on...

**Comment by salvoravida** [comment]
it's so strange i have just added a new build for "module". not touched the main build that i think is used on iOS.

**Comment by raaaar** [comment]
It was a glitch in testing methodology, everything works. Cleaned up a little and pulled in manually. Thanks a lot!

**Pull request closed without merging**
